import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {IrcPiBot} from '../.runtime/pi/packages/coding-agent/src/cuse/bot.ts';import {resolveIrcConfig} from '../.runtime/pi/packages/coding-agent/src/cuse/run.ts';
for(const override of [false,true])test('executed bot registration joins '+(override?'explicit control override':'default #cuse')+' plus independent channels',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'cuse-default-'));const env={IRC_SERVER:'synthetic.invalid',IRC_CHANNELS:'#other',...(override?{IRC_CONTROL_CHANNEL:'#custom',IRC_NICK:'customnick'}:{})};const config=resolveIrcConfig({},env,dir);const joins:string[]=[];const ensured:string[]=[];let connected:any;
 class Irc extends EventEmitter{connect(options:any){connected=options;}join(channel:string){joins.push(channel);this.emit('join',{nick:config.nick,channel});}say(){}quit(){}changeNick(){}}
 const irc=new Irc();const bot=new IrcPiBot({...config,cwd:dir,agentDir:dir,sessionDir:join(dir,'sessions'),workspaceRoot:join(dir,'work'),desktops:{ensure:async(room:string)=>{ensured.push(room);return{id:'synthetic-'+room,name:room,state:'running'};}} as any,modelRuntime:{} as any,createResources:async()=>{throw Error('unused');},openSession:async()=>{throw Error('unused');},forkSession:()=>{throw Error('unused');},log:()=>{},createClient:()=>irc as any,sendSpacingMs:0});
 try{await bot.start();assert.equal(connected.nick,override?'customnick':'cuse');irc.emit('registered',{nick:config.nick});for(let n=0;n<8;n++)await new Promise(r=>setTimeout(r,2));assert.deepEqual(joins,[override?'#custom':'#cuse','#other']);assert.deepEqual(ensured,joins);assert.deepEqual([...bot.joinedChannels],joins);const records=bot.store.entries();assert.equal(records.length,2);assert.notEqual(records[0][1].desktopId,records[1][1].desktopId);}finally{await bot.close();rmSync(dir,{recursive:true,force:true});}
});
test('Docker and entrypoint expose #cuse/cuse defaults without overriding explicit config',()=>{const docker=readFileSync(new URL('../Dockerfile',import.meta.url),'utf8');const entry=readFileSync(new URL('../entrypoint.sh',import.meta.url),'utf8');assert.ok(docker.includes('IRC_CONTROL_CHANNEL=#cuse'));assert.ok(docker.includes('IRC_NICK=cuse'));assert.ok(entry.includes('IRC_CONTROL_CHANNEL="'+String.fromCharCode(36)+'{IRC_CONTROL_CHANNEL:-#cuse}"'));assert.ok(entry.includes('IRC_NICK="'+String.fromCharCode(36)+'{IRC_NICK:-cuse}"'));});
