import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {IrcPiBot} from '../.runtime/pi/packages/coding-agent/src/cuse/bot.ts';
import {containFault} from '../.runtime/pi/packages/coding-agent/src/cuse/run.ts';
import {failureDetail,JoinRefusedError} from '../.runtime/pi/packages/coding-agent/src/cuse/join.ts';
import {PublicError,publicError} from '../.runtime/pi/packages/coding-agent/src/cuse/public-error.ts';
import {UnsupportedDesktopForkError} from '../.runtime/pi/packages/coding-agent/src/cuse/computer-use.ts';
const CANARY='SECRET_CANARY_access_refresh https://auth.invalid/callback?code=SECRET_CANARY';
const bad=()=>{const e=new Error(CANARY);e.stack=CANARY;throw e;};
const settle=async()=>{for(let n=0;n<5;n++)await new Promise(r=>setTimeout(r,2));};
function fixture(failure:string){
 const dir=mkdtempSync(join(tmpdir(),'cuse-boundary-'));const logs:string[]=[];const messages:string[]=[];
 const run=(key:string)=>{if(failure===key)bad();};
 class Irc extends EventEmitter{connect(){} changeNick(){} quit(){} part(){run('part');} join(channel:string){run('join');if(failure==='joinRefused')this.emit('irc error',{error:'too_many_channels',reason:CANARY,channel});else this.emit('join',{nick:'cuse',channel});}say(_target:string,text:string){messages.push(text);run('send');}}
 const irc=new Irc();const model={provider:'openai-codex',id:'gpt-5.4',name:'safe'};
 const session=(room:string)=>({sessionId:room,sessionFile:join(dir,room+'.jsonl'),busy:false,watch:()=>()=>{},prompt:async()=>{run('prompt');return {text:'safe',steered:false};},abort:async()=>{},availableThinkingLevels:()=>{run('thinking');return ['off','high'];},thinkingLevel:()=> 'off',modelLabel:()=> 'openai-codex/gpt-5.4',setModel:async()=>{run('setModel');},setThinkingLevel:()=>{run('thinking');},cycleThinkingLevel:()=>{},compact:async()=>{run('compact');},reload:async()=>{run('reload');}});
 const desktops={ensure:async(room:string)=>{run('ensure');return{id:room,name:room,state:'running'};},get:async()=>{run('get');return{id:'safe',state:'running'};},lifecycle:async()=>{run('lifecycle');return{id:'safe',state:'running'};},viewer:()=> 'https://viewer.invalid/safe',assertDiskForkSupported:()=>{if(failure==='fork')bad();throw new UnsupportedDesktopForkError();}} as any;
 const bot=new IrcPiBot({server:'synthetic.invalid',port:6667,tls:false,nick:'cuse',channels:[],controlChannel:'#control',addressedOnly:true,statePath:join(dir,'state.json'),workspaceRoot:join(dir,'work'),cwd:dir,agentDir:dir,sessionDir:join(dir,'sessions'),desktops,modelRuntime:{getAvailable:async()=>{run('available');return[model];}} as any,createResources:async()=>{throw Error('not called');},openSession:async(room:string)=>{run('open');return session(room) as any;},forkSession:()=>{throw Error('not called');},log:s=>logs.push(s),createClient:()=>irc as any,sendSpacingMs:0,joinTimeoutMs:10});
 return {bot,irc,logs,messages,dir};
}
for(const [failure,command]of [['prompt','cuse: hello'],['open','cuse: hello'],['available',',model'],['setModel',',model gpt'],['reload',',reload'],['compact',',compact'],['thinking',',thinking high'],['get',',desktop'],['lifecycle',',sleep'],['fork',',fork #target'],['join',',join #target'],['joinRefused',',join #target'],['part',',part #target']] as const)test('public command boundary withholds '+failure,async()=>{
 const f=fixture(failure);try{await f.bot.start();f.bot.store.set('#control',{desktopId:'remembered',createdAt:1});f.irc.emit('privmsg',{nick:'tester',target:'#control',message:command});await settle();assert.ok(f.messages.length>0);assert.ok(![...f.logs,...f.messages].join(' ').includes('SECRET_CANARY'));assert.ok(![...f.logs,...f.messages].join(' ').includes('auth.invalid'));}finally{await f.bot.close();rmSync(f.dir,{recursive:true,force:true});}
});
for(const failure of ['ensure','send','join'])test('event/log boundary withholds '+failure,async()=>{const f=fixture(failure);try{await f.bot.start();if(failure==='ensure')f.irc.emit('join',{nick:'cuse',channel:'#target'});if(failure==='send')f.bot.say('#target','safe response');if(failure==='join')f.irc.emit('registered',{nick:'cuse'});await settle();assert.ok(f.logs.length>0);assert.ok(![...f.logs,...f.messages].join(' ').includes('SECRET_CANARY'));}finally{await f.bot.close();rmSync(f.dir,{recursive:true,force:true});}});
for(const failure of ['prompt','open'])test('cross-channel catch withholds '+failure,async()=>{const f=fixture(failure);try{await f.bot.start();f.irc.emit('join',{nick:'cuse',channel:'#target'});await settle();await f.bot.send({room:'#control',channel:'#target',text:'cuse: hello'});await settle();assert.ok(f.messages.some(x=>x.includes('details were withheld')));assert.ok(![...f.logs,...f.messages].join(' ').includes('SECRET_CANARY'));}finally{await f.bot.close();rmSync(f.dir,{recursive:true,force:true});}});
test('runtime channel/outside faults and server reasons never stringify secret failures',async()=>{const f=fixture('none');try{await f.bot.start();const error=new Error(CANARY);f.bot.onChannelFault('#control',error);containFault('exception',f.bot,s=>f.logs.push(s))(error);f.irc.emit('irc error',{error:CANARY,reason:CANARY});assert.ok(f.logs.length===3);assert.ok(!f.logs.join(' ').includes('SECRET_CANARY'));}finally{await f.bot.close();rmSync(f.dir,{recursive:true,force:true});}});
test('only owned codes provide safe guidance; mutated messages, names, stacks, causes and stringification ignored',()=>{let strings=0;assert.match(publicError({toString:()=>{strings++;return CANARY;}}),/withheld/);assert.equal(strings,0);const e=new PublicError('codexAuth');e.message=CANARY;e.stack=CANARY;e.cause=new Error(CANARY);assert.match(publicError(e),/private administrator.*reauthenticate/);assert.ok(!publicError(e).includes('SECRET_CANARY'));const fork=new UnsupportedDesktopForkError();fork.message=CANARY;assert.match(publicError(fork),/Disk snapshot fork is unavailable/);assert.match(publicError(new PublicError('joinedOnly')),/already joined/);assert.match(publicError(new Error('irc_send requires an already joined IRC channel')),/withheld/);const refused=new JoinRefusedError('#safe',CANARY);(refused as any).detail=CANARY;assert.ok(!failureDetail(refused).includes('SECRET_CANARY'));});
test('startup, extension and failed agent/tool event wiring use controlled boundaries',()=>{for(const name of ['main','run','channel-session']){const source=readFileSync(new URL('../src/'+name+'.ts',import.meta.url),'utf8');assert.ok(!source.includes('String(error)'));assert.ok(!source.includes('error.message'));assert.ok(!source.includes('error.stack'));assert.match(source,/publicError/);}const source=readFileSync(new URL('../src/channel-session.ts',import.meta.url),'utf8');assert.ok(source.includes("event.isError ? publicError(undefined)"));assert.ok(source.includes('message.stopReason === "error"'));});
